name: macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute:
    runs-on: macos-latest

    steps:
      - name: Checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Make scripts executable
        run: |
          which zsh
          sudo chsh -s $(which zsh)
          chmod +x ./catalog.sh
          chmod +x ./cookies.sh

      - name: Execute scripts
        run: |
          sudo chsh -s $(which zsh)
          echo "Running script for exercise 1 - HTTP from the terminal"
          ./catalog.sh 449
          echo "========================================================="
          echo "---------------------------------------------------------"
          echo "Running script for exercise 2 - Cookies from the terminal"
          ./cookies.sh
